### ISSUE TITLE
Error when strictNullChecks are enabled

### ISSUE THREAD

**Issue by tmueller** [0xfede/fseh#1]
Hi,

I want to use fseh for a small project. Howerever, when compiling with strictNullChecks set true, I get the following errors:

```
[ts] Property '['exit']' of type '((...args: any[]) => any) | undefined' is not assignable to string index type  '(...args: any[]) => any'.
[ts] Property '['entry']' of type '((...args: any[]) => any) | undefined' is not assignable to string index type '(...args: any[]) => any'.
[ts] Property '['*']' of type '((...args: any[]) => any) | undefined' is not assignable to string index type '(...args: any[]) => any'.
```

The reason seems to be, that all types in an interface must match an index type. So changing `[name: string]: (...args: any[]) => any;` to `[name: string]: ((...args: any[]) => any) | undefined;` might be the correct solution for this error.

**Comment by 0xfede** [comment]
Hi, it should be fixed, thanks for spotting it :-)

The new npm package (2.0.4) should already be live.

**Comment by tmueller** [comment]
Thanks for the lightning fast fix :)

Am 06.03.2017 16:29 schrieb "Federico Pinna" <notifications@github.com>:
